### ISSUE TITLE
Mod always requiring TAC or SimpleLife

### ISSUE THREAD

**Issue by VassilyDev** [zer0Kerbal/MoarKerbals#4]
**Describe the bug**
The cloning process requires biomass also when MKS, TAC or other life-support mods are not installed.

 - OS: Win10x64
 - KSP: 1.11.2
 - Version 1.1.0.0

I had to edit this line of ResourceMods.cfg to get it working.

`@recipeIngredients = ElectricCharge,BioMass`
`@recipeAmounts = 15000,15`

TO:

`@recipeIngredients = ElectricCharge`
`@recipeAmounts = 15000`

**Comment by zer0Kerbal** [comment]
First, thank you @VassilyDev .

In that file, everything is commented out so it shouldn't be affecting anything; (that is the // at the start of each line)

I believe the file is a leftover from the old version of MoarKerbals (before I adopted it); it should be updated for the different lifesupport mods in the future which is why it is still around and not gone.

Did you uncomment the file? By default all kloning/kuddling require EC, ore, and oxidizer.

**Comment by VassilyDev** [comment]
I just installed the mod and launched a ship to test the mod, and it required BioMass to work.
So I did the correction in the file but I did not uncomment anything, just removed BioMass and the relative amount required.

**Comment by zer0Kerbal** [comment]
@VassilyDev okay, where did you download it from? I have been unable to find an uncommented version of that file.

**Comment by VassilyDev** [comment]
I'm 99% sure it is the last version from GitHub.
